type state01_AL.txt | find "TMIN" > AL\TMIN.TXT
type state02_AZ.txt | find "TMIN" > AZ\TMIN.TXT
type state03_AR.txt | find "TMIN" > AR\TMIN.TXT
type state04_CA.txt | find "TMIN" > CA\TMIN.TXT
type state05_CO.txt | find "TMIN" > CO\TMIN.TXT
type state06_CT.txt | find "TMIN" > CT\TMIN.TXT
type state07_DE.txt | find "TMIN" > DE\TMIN.TXT
type state08_FL.txt | find "TMIN" > FL\TMIN.TXT
type state09_GA.txt | find "TMIN" > GA\TMIN.TXT
type state10_ID.txt | find "TMIN" > ID\TMIN.TXT
type state11_IL.txt | find "TMIN" > IL\TMIN.TXT
type state12_IN.txt | find "TMIN" > IN\TMIN.TXT
type state13_IA.txt | find "TMIN" > IA\TMIN.TXT
type state14_KS.txt | find "TMIN" > KS\TMIN.TXT
type state15_KY.txt | find "TMIN" > KY\TMIN.TXT
type state16_LA.txt | find "TMIN" > LA\TMIN.TXT
type state17_ME.txt | find "TMIN" > ME\TMIN.TXT
type state18_MD.txt | find "TMIN" > MD\TMIN.TXT
type state19_MA.txt | find "TMIN" > MA\TMIN.TXT
type state20_MI.txt | find "TMIN" > MI\TMIN.TXT
type state21_MN.txt | find "TMIN" > MN\TMIN.TXT
type state22_MS.txt | find "TMIN" > MS\TMIN.TXT
type state23_MO.txt | find "TMIN" > MO\TMIN.TXT
type state24_MT.txt | find "TMIN" > MT\TMIN.TXT
type state25_NE.txt | find "TMIN" > NE\TMIN.TXT
type state26_NV.txt | find "TMIN" > NV\TMIN.TXT
type state27_NH.txt | find "TMIN" > NH\TMIN.TXT
type state28_NJ.txt | find "TMIN" > NJ\TMIN.TXT
type state29_NM.txt | find "TMIN" > NM\TMIN.TXT
type state30_NY.txt | find "TMIN" > NY\TMIN.TXT
type state31_NC.txt | find "TMIN" > NC\TMIN.TXT
type state32_ND.txt | find "TMIN" > ND\TMIN.TXT
type state33_OH.txt | find "TMIN" > OH\TMIN.TXT
type state34_OK.txt | find "TMIN" > OK\TMIN.TXT
type state35_OR.txt | find "TMIN" > OR\TMIN.TXT
type state36_PA.txt | find "TMIN" > PA\TMIN.TXT
type state37_RI.txt | find "TMIN" > RI\TMIN.TXT
type state38_SC.txt | find "TMIN" > SC\TMIN.TXT
type state39_SD.txt | find "TMIN" > SD\TMIN.TXT
type state40_TN.txt | find "TMIN" > TN\TMIN.TXT
type state41_TX.txt | find "TMIN" > TX\TMIN.TXT
type state42_UT.txt | find "TMIN" > UT\TMIN.TXT
type state43_VT.txt | find "TMIN" > VT\TMIN.TXT
type state44_VA.txt | find "TMIN" > VA\TMIN.TXT
type state45_WA.txt | find "TMIN" > WA\TMIN.TXT
type state46_WV.txt | find "TMIN" > WV\TMIN.TXT
type state47_WI.txt | find "TMIN" > WI\TMIN.TXT
type state48_WY.txt | find "TMIN" > WY\TMIN.TXT