type state01_AL.txt | find "TMAX" > AL\TMAX.TXT
type state02_AZ.txt | find "TMAX" > AZ\TMAX.TXT
type state03_AR.txt | find "TMAX" > AR\TMAX.TXT
type state04_CA.txt | find "TMAX" > CA\TMAX.TXT
type state05_CO.txt | find "TMAX" > CO\TMAX.TXT
type state06_CT.txt | find "TMAX" > CT\TMAX.TXT
type state07_DE.txt | find "TMAX" > DE\TMAX.TXT
type state08_FL.txt | find "TMAX" > FL\TMAX.TXT
type state09_GA.txt | find "TMAX" > GA\TMAX.TXT
type state10_ID.txt | find "TMAX" > ID\TMAX.TXT
type state11_IL.txt | find "TMAX" > IL\TMAX.TXT
type state12_IN.txt | find "TMAX" > IN\TMAX.TXT
type state13_IA.txt | find "TMAX" > IA\TMAX.TXT
type state14_KS.txt | find "TMAX" > KS\TMAX.TXT
type state15_KY.txt | find "TMAX" > KY\TMAX.TXT
type state16_LA.txt | find "TMAX" > LA\TMAX.TXT
type state17_ME.txt | find "TMAX" > ME\TMAX.TXT
type state18_MD.txt | find "TMAX" > MD\TMAX.TXT
type state19_MA.txt | find "TMAX" > MA\TMAX.TXT
type state20_MI.txt | find "TMAX" > MI\TMAX.TXT
type state21_MN.txt | find "TMAX" > MN\TMAX.TXT
type state22_MS.txt | find "TMAX" > MS\TMAX.TXT
type state23_MO.txt | find "TMAX" > MO\TMAX.TXT
type state24_MT.txt | find "TMAX" > MT\TMAX.TXT
type state25_NE.txt | find "TMAX" > NE\TMAX.TXT
type state26_NV.txt | find "TMAX" > NV\TMAX.TXT
type state27_NH.txt | find "TMAX" > NH\TMAX.TXT
type state28_NJ.txt | find "TMAX" > NJ\TMAX.TXT
type state29_NM.txt | find "TMAX" > NM\TMAX.TXT
type state30_NY.txt | find "TMAX" > NY\TMAX.TXT
type state31_NC.txt | find "TMAX" > NC\TMAX.TXT
type state32_ND.txt | find "TMAX" > ND\TMAX.TXT
type state33_OH.txt | find "TMAX" > OH\TMAX.TXT
type state34_OK.txt | find "TMAX" > OK\TMAX.TXT
type state35_OR.txt | find "TMAX" > OR\TMAX.TXT
type state36_PA.txt | find "TMAX" > PA\TMAX.TXT
type state37_RI.txt | find "TMAX" > RI\TMAX.TXT
type state38_SC.txt | find "TMAX" > SC\TMAX.TXT
type state39_SD.txt | find "TMAX" > SD\TMAX.TXT
type state40_TN.txt | find "TMAX" > TN\TMAX.TXT
type state41_TX.txt | find "TMAX" > TX\TMAX.TXT
type state42_UT.txt | find "TMAX" > UT\TMAX.TXT
type state43_VT.txt | find "TMAX" > VT\TMAX.TXT
type state44_VA.txt | find "TMAX" > VA\TMAX.TXT
type state45_WA.txt | find "TMAX" > WA\TMAX.TXT
type state46_WV.txt | find "TMAX" > WV\TMAX.TXT
type state47_WI.txt | find "TMAX" > WI\TMAX.TXT
type state48_WY.txt | find "TMAX" > WY\TMAX.TXT